export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  pagarmeApiUrl: process.env.PAGARME_API_URL ?? "https://api.pagar.me/core/v5",
  pagarmeApiKey: process.env.PAGARME_API_KEY ?? "",
  pagarmePublicKey: process.env.PAGARME_PUBLIC_KEY ?? "",
  pagarmeAccountId: process.env.PAGARME_ACCOUNT_ID ?? "",
  pagarmeplatformRecipientId: process.env.PAGARME_PLATFORM_RECIPIENT_ID ?? "",
  pagarmeorganizerRecipientId: process.env.PAGARME_ORGANIZER_RECIPIENT_ID ?? "",
};
